platform:
  - x64

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly

matrix:
  fast_finish: true

install:
  - chcp
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:CHANNEL}-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -Vv
  - cargo -V

build_script:
  - cargo build

test_script:
  - cargo test
