[workspace]
license = "MIT"
members = [
    "pasta_di",
#    "pasta_parser",
#    "pasta_recipe",
#    "pasta_stage",
#    "pasta_viewer",
#    "shiori_hglobal",
#    "shiori3",
#    "pasta",
]

[replace]
# "winapi:0.3" =  {version = "0.3", features = ["winerror", "d3d11", "dcomp"]}
