[package]
authors = ["ekicyou <dot.station@gmail.com>"]
description = "pasta script parser"
edition = "2018"
keywords = ["pasta", "ghost", "shiori", "ukagaka"]
license = "MIT"
name = "pasta_script"
readme = "README.md"
repository = "https://github.com/ekicyou/pasta-rs"
version = "0.5.0"

[dependencies]
itertools = "0.9"
log = "0.4"
pest = "2.1"
pest_consume = "1.0"
pest_derive = "2.1"
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.8"
