[package]
authors = ["ekicyou <dot.station@gmail.com>"]
description = "pasta parser"
edition = "2018"
keywords = ["pasta", "ghost", "shiori", "ukagaka"]
license = "MIT"
name = "pasta_parser"
readme = "README.md"
repository = "https://github.com/ekicyou/pasta-rs"
version = "0.3.0"

[dependencies]
itertools = "0.9"
log = "0.4"
pest = "2.1"
pest_derive = "2.1"

[dev-dependencies]
env_logger = "0.7"
