[package]
authors = ["ekicyou <dot.station@gmail.com>"]
description = "pasta script parser"
edition = "2018"
keywords = ["pasta", "ghost", "shiori", "ukagaka"]
license = "MIT"
name = "pasta_script"
readme = "README.md"
repository = "https://github.com/ekicyou/pasta-rs"
version = "0.3.0"

[dependencies]
base32 = "0.4"
itertools = "0.9"
log = "0.4"
pest = "2.1"
pest_consume = "1.0"
pest_derive = "2.1"

[dependencies.rhai]
branch = "master"
features = ["only_i32", "unicode-xid-ident", "internals", "serde"]
git = "https://github.com/jonathandturner/rhai"
version = "0.18"

[dev-dependencies]
env_logger = "0.7"
