[package]
name = "shiori_gen"
version = "0.1.0"
authors = ["ekicyou <dot.station@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
squote = "0.1"
syn = "1.0"
