[package]
name = "pasta_core"
version = "0.1.0"
authors = ["ekicyou <dot.station@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
log = "0.4"
once_cell = "1.5"
